# https://github.com/postgis/docker-postgis
# https://github.com/docker-library/docs/blob/master/postgres/README.md
# https://github.com/geoserver/docker
# https://github.com/postgis/docker-postgis/issues/187

services:
    apache:
        image: httpd:latest
        restart: no
        ports:
            - "8000:80"
        volumes:
            - ./.cache/volumes/apache/frontend:/usr/local/apache2/htdocs/
        depends_on:
            - geoserver

    geoserver:
        image: docker.osgeo.org/geoserver:2.26.2
        restart: no
        ports:
            - "8080:8080"
        environment:
            GEOSERVER_ADMIN_USER: admin
            GEOSERVER_ADMIN_PASSWORD: geoserver
            # SKIP_DEMO_DATA: true
            # INSTALL_EXTENSIONS: true
            # STABLE_EXTENSIONS: wps,csw
            EXTRA_JAVA_OPTS: -Xms1G -Xmx2G
            POSTGRES_JNDI_ENABLED: true
            POSTGRES_HOST: postgis
            POSTGRES_PORT: 5432
            POSTGRES_DB: gis
            POSTGRES_USERNAME: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_JNDI_RESOURCE_NAME: jdbc/postgres

        volumes:
            - ./.cache/volumes/geoserver/geoserver_data:/opt/geoserver/data_dir:Z
            # - ./additional_libs:/opt/additional_libs:Z # by mounting this we can install libs from host on startup
        depends_on:
            - postgis
        healthcheck:
            test: curl --fail "http://localhost:8080/geoserver/web/wicket/resource/org.geoserver.web.GeoServerBasePage/img/logo.png" || exit 1
            interval: 1m
            retries: 3
            timeout: 20s

    postgis:
        image: postgis/postgis:16-3.5
        restart: no
        ports:
            - "127.0.0.1:5432:5432"
        environment:
            POSTGRES_DB: gis
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./.cache/volumes/postgresql/postgresql_data:/var/lib/postgresql/data:Z
            - ./server/docker//10_postgis.sh:/docker-entrypoint-initdb.d/10_postgis.sh
        healthcheck:
            test: pg_isready -U postgres -h localhost -t 5 || exit 1
            interval: 10s
            retries: 5
            timeout: 10s
