#!/bin/bash

set -euo pipefail

echo "
REACT_APP_PAGE_SIZE=100
REACT_APP_API_BASE_URL=http://localhost:8000
REACT_APP_IDLE_SECONDS_LOGOUT=6000
REACT_APP_GOOGLE_ANALYTICS_CODE=
REACT_APP_SENTRY_DSN=
REACT_APP_MAPBOX_TOKEN=
"
