#!/bin/bash

set -euo pipefail

echo "
REACT_APP_PAGE_SIZE=600
REACT_APP_API_BASE_URL=http://localhost:8000
REACT_APP_IDLE_SECONDS_LOGOUT=6000
REACT_APP_SENTRY_DSN=
REACT_APP_MAPBOX_TOKEN=
REACT_APP_POI_WFS_URL='http://localhost:3000/geoserver/wfs'
REACT_APP_POI_WFS_TYPENAMES='isocronas:poi'
"
